# Patient summary generation and export
# This module creates a deterministic doctor-facing summary
# from the stored triage session.
# It does NOT diagnose the patient.

from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import PlainTextResponse
from motor.motor_asyncio import AsyncIOMotorDatabase
from pydantic import BaseModel

from api.auth import get_current_user
from db.mongo import get_db
from db.models import UserDB


router = APIRouter(
    prefix="/summary",
    tags=["summary"],
)

# Response Schema
class PatientSummaryResponse(BaseModel):
    id: str
    triage_session_id: str
    user_id: str | None
    summary_text: str
    urgency: str
    extracted_symptoms: list[str]
    matched_red_flags: list[dict]
    recommended_facility_types: list[str]
    generated_at: str


# Summary Builder
def _build_summary_text(triage_doc: dict,) -> str:
    lines = [
        "PATIENT SUMMARY",
        "AI-ASSISTED TRIAGE — DECISION SUPPORT ONLY",
        "=" * 60,
        "",
        f"Language: {triage_doc.get('language', 'Not provided')}",
        f"Age: {triage_doc.get('age', 'Not provided')}",
        f"Sex: {triage_doc.get('sex', 'Not provided')}",
        (
            "Symptom duration (hours): "
            f"{triage_doc.get('duration_hours', 'Not provided')}"
        ),
        "",
        "REPORTED COMPLAINT",
        "-" * 30,
        triage_doc.get(
            "raw_text",
            "Not provided",
        ),
        "",
        "EXTRACTED SYMPTOMS",
        "-" * 30,
    ]

    symptoms = triage_doc.get(
        "extracted_symptoms",
        [],
    )

    if symptoms:
        lines.extend(
            f"- {symptom}"
            for symptom in symptoms
        )
    else:
        lines.append("- None recognized")

    urgency = triage_doc.get(
        "urgency",
        "unknown",
    )

    lines.extend(
        [
            "",
            "TRIAGE URGENCY",
            "-" * 30,
            urgency.upper(),
            "",
        ]
    )

    flags = triage_doc.get(
        "matched_red_flags",
        [],
    )

    lines.append("DANGER SIGNS")

    if flags:
        lines.append("-" * 30)
        for flag in flags:
            lines.append(
                f"[{flag.get('code', 'N/A')}] "
                f"{flag.get('label', 'Unknown flag')}"
            )
            if flag.get("advice"):
                lines.append(
                    f"Advice: {flag['advice']}"
                )
    else:
        lines.append(
            "No danger signs detected by the rule-based triage engine."
        )

    specialties = triage_doc.get(
        "recommended_specialties",
        [],
    )

    lines.extend(
        [
            "",
            "RECOMMENDED SPECIALTIES",
            "-" * 30,
            (
                ", ".join(specialties)
                if specialties
                else "General Medicine"
            ),
            "",
            "=" * 60,
            "DISCLAIMER",
            (
                "This summary is generated by an automated "
                "decision-support system. It is NOT a medical "
                "diagnosis and does not replace clinical judgment."
            ),
        ]
    )

    return "\n".join(lines)

# Helper
def _summary_response(doc: dict,) -> PatientSummaryResponse:
    return PatientSummaryResponse(
        id=str(doc["_id"]),
        triage_session_id=doc["triage_session_id"],
        user_id=doc.get("user_id"),
        summary_text=doc["summary_text"],
        urgency=doc["urgency"],
        extracted_symptoms=doc.get(
            "extracted_symptoms",
            [],
        ),
        matched_red_flags=doc.get(
            "matched_red_flags",
            [],
        ),
        recommended_facility_types=doc.get(
            "recommended_facility_types",
            [],
        ),
        generated_at=str(
            doc["generated_at"]
        ),
    )

# Generate Summary
@router.post(
    "/{triage_session_id}",
    response_model=PatientSummaryResponse,
    status_code=status.HTTP_201_CREATED,
)
async def generate_summary(
    triage_session_id: str,
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: UserDB = Depends(get_current_user),
):
    triage_doc = await db.triage_sessions.find_one(
        {"_id": triage_session_id}
    )
    if not triage_doc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Triage session not found.",
        )
    # A patient can only generate a summary
    # for their own triage session.
    if triage_doc.get("user_id") != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to access this triage session.",
        )
    # Avoid generating duplicate summaries.
    existing = await db.patient_summaries.find_one(
        {
            "triage_session_id": triage_session_id
        }
    )
    if existing:
        return _summary_response(existing)
    summary_text = _build_summary_text(
        triage_doc
    )
    urgency = triage_doc.get(
        "urgency",
        "routine",
    )
    if urgency == "emergency":
        recommended_facility_types = [
            "hospital",
            "ambulance",
        ]
    elif urgency == "urgent":
        recommended_facility_types = [
            "phc",
            "chc",
            "hospital",
        ]
    else:
        recommended_facility_types = [
            "phc",
            "chc",
        ]
    doc = {
        "_id": str(uuid4()),
        "triage_session_id": triage_session_id,
        "user_id": triage_doc.get("user_id"),
        "summary_text": summary_text,
        "urgency": urgency,
        "extracted_symptoms": triage_doc.get(
            "extracted_symptoms",
            [],
        ),
        "matched_red_flags": triage_doc.get(
            "matched_red_flags",
            [],
        ),
        "recommended_facility_types": (
            recommended_facility_types
        ),
        "generated_at": triage_doc.get(
            "created_at"
        ),
    }
    await db.patient_summaries.insert_one(
        doc
    )
    return _summary_response(doc)

# Get Summary
@router.get(
    "/{triage_session_id}",
    response_model=PatientSummaryResponse,
)
async def get_summary(
    triage_session_id: str,
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: UserDB = Depends(get_current_user),
):
    doc = await db.patient_summaries.find_one(
        {
            "triage_session_id": triage_session_id
        }
    )
    if not doc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Summary not found for this session.",
        )
    if doc.get("user_id") != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to access this summary.",
        )
    return _summary_response(doc)

# Export Summary
@router.get(
    "/{triage_session_id}/export",
    response_class=PlainTextResponse,
)
async def export_summary_text(
    triage_session_id: str,
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: UserDB = Depends(get_current_user),
):
    doc = await db.patient_summaries.find_one(
        {
            "triage_session_id": triage_session_id
        }
    )
    if not doc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Summary not found for this session.",
        )
    if doc.get("user_id") != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to export this summary.",
        )
    return doc["summary_text"]


# List User Summaries
@router.get(
    "",
    response_model=list[PatientSummaryResponse],
)
async def list_summaries_for_user(
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: UserDB = Depends(get_current_user),
    limit: int = 20,
):
    limit = max(
        1,
        min(limit, 100),
    )
    cursor = (
        db.patient_summaries
        .find(
            {
                "user_id": current_user.id
            }
        )
        .sort(
            "generated_at",
            -1,
        )
        .limit(limit)
    )
    docs = await cursor.to_list(
        length=limit
    )
    return [
        _summary_response(doc)
        for doc in docs
    ]